---
title: "README"
output: html_document
date: '2022-12-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Code used for the analysis of the RNA-seq datasets produced in this study. Original fastq files deposited in https://ega-archive.org/, under the accession number     .

# Getting started

Different folders are included in this repository:

* RNA-seq_Park7_KnockOut_mice: Contains the analysis of 6 datasets including Park7 Knockout and wildtype mice: FemaleS 3 months of age, Males 3 months of age, FemaleS 8 months of age, MaleS 8 months of age first cohort, MaleS 8 months of age second cohort, MaleS 8 months of age first and second cohort together

* RNA-seq_Sex-differences_8months_mice: Contains the analysis of 1 dataset including male and female wildtype mice at 8 months of age

* RNA-seq_mouse_primary_astrocytes: Contains the analysis of 1 dataset of astrocytes treated with different siRNAs and their respective scramble: siPark7, siNfe2l2 and siCyp1b1 treated astrocytes

